name: CI
on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Checkout & Build & Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: php-xray-symfony-bundle
      - name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: php-xray-symfony-bundle
          options: --user root --volume ${{ github.workspace }}:${{ github.workspace }} --workdir ${{ github.workspace }}
          run: |
            composer test